// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAad7AfFMqhUD-a7ojwOlIXmytFnL-DEnE',
    appId: '1:609029826630:web:9cc52b52254fc2cdbdc247',
    messagingSenderId: '609029826630',
    projectId: 'chitraapp-8d61f',
    authDomain: 'chitraapp-8d61f.firebaseapp.com',
    storageBucket: 'chitraapp-8d61f.appspot.com',
    measurementId: 'G-30Q13DCXBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9zm1HgCTgSxf13ZIj7TQyD65FDic_u0',
    appId: '1:609029826630:android:b9341a38ae08074cbdc247',
    messagingSenderId: '609029826630',
    projectId: 'chitraapp-8d61f',
    storageBucket: 'chitraapp-8d61f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vnlu9JOT-J-4n3BdOy3AZSq9WKJ7mG8',
    appId: '1:609029826630:ios:4df8e4678ebf7f0dbdc247',
    messagingSenderId: '609029826630',
    projectId: 'chitraapp-8d61f',
    storageBucket: 'chitraapp-8d61f.appspot.com',
    iosBundleId: 'com.example.chitraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3vnlu9JOT-J-4n3BdOy3AZSq9WKJ7mG8',
    appId: '1:609029826630:ios:4df8e4678ebf7f0dbdc247',
    messagingSenderId: '609029826630',
    projectId: 'chitraapp-8d61f',
    storageBucket: 'chitraapp-8d61f.appspot.com',
    iosBundleId: 'com.example.chitraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAad7AfFMqhUD-a7ojwOlIXmytFnL-DEnE',
    appId: '1:609029826630:web:6ac4afda480efad1bdc247',
    messagingSenderId: '609029826630',
    projectId: 'chitraapp-8d61f',
    authDomain: 'chitraapp-8d61f.firebaseapp.com',
    storageBucket: 'chitraapp-8d61f.appspot.com',
    measurementId: 'G-3J0RECY6CN',
  );
}
